### ISSUE TITLE
st2web liveness probe failing on v0.14.0 and v0.15.0

### ISSUE THREAD

**Issue by AngryDeveloper** [StackStorm/stackstorm-ha#106]
I'm currently upgrading our HA install from version v0.13.0 to the last possible version.

Going from v0.13.0 to v0.14.0 I noticed that the liveness probe for st2web were failing 

> Warning  Unhealthy  2m55s (x9 over 4m15s)  kubelet, worker3 Liveness probe failed: Get https://x.x.x.x:443/: dial tcp x.x.x.x:443: connect: connection refused

Digging a bit I found that the Dockerfile for st2web version 3.1dev was modified to disable HTTPS by default. (see https://github.com/StackStorm/st2-dockerfiles/blob/v3.1.0/st2web/Dockerfile#L20)

I'm working on a PR to reenable HTTPS  for the chart's version < **v0.16.0**

**Comment by armab** [comment]
Yes, `st2web` since that change is listening on `HTTP` only. This conforms better with the other Helm chart practices and removes SSL cert requirements from the default Helm Values.

Please use Ingress controller or LoadBalancer if you need additional `HTTPs` layer in front of `st2web`.

For more context see:
* https://github.com/StackStorm/stackstorm-ha#ingress
* https://github.com/StackStorm/stackstorm-ha#st2web
* https://github.com/StackStorm/stackstorm-ha/issues/6
