### ISSUE TITLE
st2ctl status shows all the st2 components not running on K8 HA Cluster

### ISSUE THREAD

**Issue by Bindu-yadav8** [StackStorm/stackstorm-ha#314]
We have migrated some of the Actions & Workflows from Azure VM to Kubernetes HA Cluster via Git. All the yaml files are located in st2client component Pod.

When st2ctl reload --register-all command is executed inside the pod, all the packs, configs, actions will be registered. However, when st2ctl status command is executed, none of the components are running. Is there any way to make this components up and running?

![image](https://user-images.githubusercontent.com/86333293/172160474-3592a3c8-1a16-444f-9d94-78b1700832e1.png)
![image](https://user-images.githubusercontent.com/86333293/172160526-75a851c6-c3cf-422c-8c8e-f46d64b89b51.png)

**Comment by armab** [comment]
`st2ctl status` reports pids of the currently running st2 processes in the local environment.

It's not expected for `st2ctl` to report the correct status in HA environment as you control the distributed services via K8s/Deployments/Pods.

I think the UX could be improved here by modifying the `st2ctl` code here:
https://github.com/StackStorm/st2/blob/419b25da9f45a92fb72549d9c4094e4cb7c6d729/st2common/bin/st2ctl#L265-L267
So ideally if it could just report a warning with the instructions to use docker/k8s primitives instead of showing "not running" for the local processes ids.

I'm leaving it as a good first issue if someone is willing to contribute the enhancement here.
